### ISSUE TITLE
SideMenu scroll when only one SideMenu used

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#11]
Hi @JoeyAndres ,
When we use only one side menu (right or left) other side tap and pull must be disable to prevent white extra partial space.
See below Images:
![screen shot 2016-02-06 at 16 35 17](https://cloud.githubusercontent.com/assets/8266479/12866834/83363610-ccf1-11e5-95f6-21c3449f93d8.png)

![screen shot 2016-02-06 at 16 43 57](https://cloud.githubusercontent.com/assets/8266479/12866835/86859d6a-ccf1-11e5-82cb-cd9db2e4ede3.png)

Please say for extra detail needs.

**Comment by cyclops24** [comment]
Oh I find a useful option for fix this.
On [this issue](https://github.com/meteoric/meteor-ionic/issues/20) on meteoric repository @nickw introduce this side option like below:

> you can pass a side option to the ionSideMenuContainer component like so:
> `{{#ionSideMenuContainer side="left"}}`
> or
> `{{#ionSideMenuContainer side="right"}}`
> or
> `{{#ionSideMenuContainer side="both"}}`

I think it's useful if you like please add this to awesome [meteoric-doc](http://meteoric-doc.meteor.com/)

**Comment by JoeyAndres** [comment]
@cyclops24 I sure will.

**Comment by JoeyAndres** [comment]
@cyclops24 http://meteoric-doc.meteor.com/ This is now in doc site.
