### ISSUE TITLE
SideMenu open when tap and pull vertically index page in demo app

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#13]
Hi @JoeyAndres ,
I update last version of demo and run on my android device and I has new issue. On the index route when I tap and pull list vertically left SideMenu opened for me. This bug happens in this version and all things OK on previous version.

**Comment by JoeyAndres** [comment]
My bad. The demo code is outdaded. I forgot to push new ones. Try it again and tell me if it is still a problem.

**Comment by cyclops24** [comment]
@JoeyAndres Thanks for your reply. Yes It's demo issue and now it's fixed.
I close this issue.
