### ISSUE TITLE
form checkbox design error on device (Android 4.2 color bleeding)

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#14]
Hi @JoeyAndres ,
Form elements OK on web but when I test in on device radio element view is buggy.
See below image for more info:
![form error](https://cloud.githubusercontent.com/assets/8266479/12872114/fdd5a0ec-cdad-11e5-8bc3-d50c6dc29fa1.png)

**Comment by JoeyAndres** [comment]
@cyclops24 I created a label web and native to deal with this issues. I'll label these stuff native, since they are problems in native devices. I'll work on them today (just woke up, so sorry for late replies).

**Comment by JoeyAndres** [comment]
@cyclops24 It looks like you built this from the old demo. Like I said in other recent issue, I forgot to push new demo code. It is now "new".

**Comment by cyclops24** [comment]
Hi @JoeyAndres,
I test again. It's OK on mobile web browser but when I run [demo app](https://github.com/JoeyAndres/ionic-demo) on mobile use `meteor run android-device` form has above issue.

**Comment by JoeyAndres** [comment]
@cyclops24 Can you send me your android version. It is working on my android emulator. I'll find a way to upload it to my phone.

**Comment by cyclops24** [comment]
@JoeyAndres My device android version is 4.2.1

**Comment by JoeyAndres** [comment]
Seems like transitions is basically done (just need your feedback on that). In the mean time, I'll start working on this.

**Comment by cyclops24** [comment]
@JoeyAndres  I try this on last demo version and It's still buggy.

**Comment by JoeyAndres** [comment]
Do you get the same in emulator. I'm trying to reproduce this bug in an andriod 4.2.\* emulator and I can't.

**Comment by JoeyAndres** [comment]
@cyclops24 I found https://github.com/driftyco/ionic/issues/1363 

The fix is now pushed in latest demo (i believe 0.1.50-alpha1). I have no way of testing (I still can't reproduce it) so tell me if it works.

**Comment by cyclops24** [comment]
Hi @JoeyAndres I test new demo app and it's fixed well.
Thanks for your attention.
