### ISSUE TITLE
backdrop not working after update

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#15]
Hi @JoeyAndres,
Backdrop not working after update.

**Comment by cyclops24** [comment]
@JoeyAndres Backdrop fixed in previous version but in new version it's again not working.

**Comment by JoeyAndres** [comment]
@cyclops24 I'll work on this after ionContent is upgraded.

**Comment by JoeyAndres** [comment]
@cyclops24 Sorry to bother you again. It's been a while since I've look at this. But can you check again? I just tested this in both my old (android 4.3) and new phone and I can see the backdrop.

**Comment by cyclops24** [comment]
Hi I test and it's fixed (you can close this issue).
But I had a issue with list in new version demo (one click on list item not working and I must tap on item multiple time to enter new page) can you test this on phone??

**Comment by JoeyAndres** [comment]
@cyclops24 Yeah for that list thing, I have figure out the problem. see [dev](http://jandres-ionic-dev.meteor.com/). I haven't publish this one yet.
