### ISSUE TITLE
content not visible on mobile

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#17]
Hi @JoeyAndres,
I dive in meteoric and try to create demo application based on your component to find bugs and report here and for more clear refer to codes. This is my demo app repository:
https://github.com/cyclops24/meteoric24-demo

My first issue that I find in meteoric is when I use simple collection each in template it's worked well and show in web mode but run on real android device (with android 4.2.1) show me a white view without side menu icon or template each result.
Show this issue in two image below.

Good result on web:
![good each](https://cloud.githubusercontent.com/assets/8266479/12947784/2807637a-d013-11e5-816d-fc3fbe8d0f26.png)

Bad result on mobile device:
![bad each](https://cloud.githubusercontent.com/assets/8266479/12947904/f3db7bda-d013-11e5-9cce-dcd6933af4c6.png)

As you see in above images header title text and side menu and also each content not visible in mobile this is my template code:

```
<template name="index">

    {{#contentFor "headerTitle"}}
        <h1 class="title">App Title</h1>
        <button class="button button-clear pull-right" data-ion-menu-toggle="right">
            {{> ionIcon icon='navicon'}}
        </button>
    {{/contentFor}}

    {{#ionView}}
        {{#ionContent}}
            <div class="padding">
                <ul>
                    {{# each messages }}
                        <li>{{title}}</li>
                    {{/each}}
                </ul>
            </div>
        {{/ionContent}}
    {{/ionView}}

</template>
```

(full source available in [my demo repository](https://github.com/cyclops24/meteoric24-demo))

**Comment by JoeyAndres** [comment]
@cyclops24 So if messages is from a collection, how do you point it to a live server? Do you do:

meteor run android-device --mobile-server my_app_name.meteor.com

Otherwise, I don't know if the collection in your local machine is being seen in the first place. Tell me if problem persist.

**Comment by JoeyAndres** [comment]
See this issue https://github.com/meteor/meteor/issues/3698

**Comment by cyclops24** [comment]
@JoeyAndres It's network issue man. I miss 4 hour for this.
Excuse me I think it's a meteoric issue (maybe with ionContent) because app header title and side menu icon lost.

Now it's worked well with `meteor run android-device` in same network.
Thanks again.
