### ISSUE TITLE
Upgrade ionSideMenu

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#27]
Current side menu is too primitive. Although snapper js was modified to be more consistent, there are still many unimplemented features. Especially wrt to 1.2.4

**Comment by cyclops24** [comment]
@JoeyAndres :+1: for SideMenu upgrade. I love SideMenu :heart:

**Comment by JoeyAndres** [comment]
Just to document the features that will be added (along with the original ionic controller) is:
- menu-close
- menu-toggle
- ionicSideMenuDelegate
- expose-aside-when

**Comment by JoeyAndres** [comment]
Note that this broke #56 due to the removal of all non-ionic controllers. This should easily be fixed. And to test expose-aside-when, try opening the [demo](http://jandres-ionic.meteor.com) in a big screen, or any non-mobile screen (> 768px).
