### ISSUE TITLE
allow ionNavBackButton without text (only icon)

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#29]
Hi @JoeyAndres,
I try to use {{>ionNavBackButton}} with empty text and try to use like this:
`{{>ionNavBackButton text=""}}`
But this component add default value for text property (Back) but I think it's not good because many times I need back button without text (only icon).
I found and see this default value set on [this file](https://github.com/JoeyAndres/meteor-ionic/blob/master/components/ionNavBackButton/ionNavBackButton.js#L76) I come here to suggest this to you.

**Comment by JoeyAndres** [comment]
@cyclops24 You are right. I'll address this. Btw, do you want to use gitter so we communicate faster. I'm not planning to sleep for a while.

**Comment by cyclops24** [comment]
@JoeyAndres  Yes I go there now. :smile:
