### ISSUE TITLE
Pass route parameter to ionItem

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#30]
Hi @JoeyAndres,
I success to pass _id through route parameter for below route:

```
this.route('category', {path: '/category/:_id', controller: 'CategoryController'});
```

This is my html:

```
{{#each categories}}
                {{#ionItem path="category" class="item-icon-left item-icon-right" }}
                    {{#ionItemContent}}
                        {{> ionIcon icon="ios-arrow-left"}}
                        {{../title}}
                        <p>{{../description}}</p>
                        {{> ionIcon icon="ios-checkmark" class="balanced"}}
                        <span class="badge badge-assertive">0</span>
                    {{/ionItemContent}}
                {{/ionItem}}
            {{/each}}
```

But who to pass title parameter for below route:

```
this.route('category', {path: '/category/:_id/:title', controller: 'CategoryController'});
```

I guess now meteoric only support _id (this specific name) because I didn't say in ionItem (I specify only path `{{#ionItem path="category"}}`) but meteoric automatically pass _id to route, but how we can pass other route parameter. Is it possible with ionItem?

**Comment by JoeyAndres** [comment]
Based on http://iron-meteor.github.io/iron-router/#pathfor I don't see a way. One of pathFor parameters is data. Which is an object. I don't see a way to assemble an object in template itself without helpers. e.g.

``` handlebars
data=(objectify x=x1 y=y1 z=z1)  <!-- generates  { x: x1, y:y1, z:z1} which we can pass to data parameter in pathFor-->
```

So you might have to build a template helper like that (I can place this in a todo project). Or for a faster solution a helper in your current template.

**Comment by cyclops24** [comment]
Thanks for replay man. I close issue. :+1:
