### ISSUE TITLE
ionContent is primitive

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#32]
Make it on par or better than http://ionicframework.com/docs/api/directive/ionContent/

This will probably contain multiple subtask since many things are below this thing.

**Comment by JoeyAndres** [comment]
Wrap content with {{#ionScroll direction="y" zoom=false}} in ios.

**Comment by JoeyAndres** [comment]
Working on this now.

**Comment by JoeyAndres** [comment]
@see http://pep.briangonzalez.org/ iscroll is too old and annoying.

**Comment by JoeyAndres** [comment]
Port ionic's controller. Decouple it and make it its own package?

**Comment by JoeyAndres** [comment]
Finally done.

**Comment by cyclops24** [comment]
Yohuuuuuuuuuuuuuuuuuu. I'm going to update package.

**Comment by JoeyAndres** [comment]
@cyclops24 note, I just pushed few more fixes. Update again.
