### ISSUE TITLE
Side Menu not working

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#4]
Hi @JoeyAndres ,
I test your [demo](http://jandres-ionic.meteor.com/) all things worked well but Side Menu not working for me. (Side Menu worked well for me on meteoric demo version)
I try using firefox and chromium.

**Comment by JoeyAndres** [comment]
Crap. I removed while working on ionScroll. I'll add it back. Sorry any headaches that I've caused.

**Comment by JoeyAndres** [comment]
It's back now.

**Comment by JoeyAndres** [comment]
The problem now is that iscroll's event is propagating to the sidemenus. Making a horizontal scroll open side menu. This should be fixed easily.

**Comment by cyclops24** [comment]
Hi,
Thanks @JoeyAndres it's working now but I don't undrestand this:

> The problem now is that iscroll's event is propagating to the sidemenus.

**Comment by JoeyAndres** [comment]
@cyclops24 Go to http://jandres-ionic.meteor.com/scroll and try scrolling right, it should open side menu, even though it should just scroll content horizontally. There are a couple of demos not in home screen.

**Comment by cyclops24** [comment]
@JoeyAndres Oh I see now.

**Comment by cyclops24** [comment]
@JoeyAndres I test Side Menu on a android device. It open but when I tap outside it's not close and when I try to close with tap and pull it's misbehave. I think this also related to iscroll because I haven't this problem with previous version.

**Comment by JoeyAndres** [comment]
@cyclops24 I still don't understand what's going on here. But try it again with my recent fix. This might be related to that "gap" issue.

**Comment by cyclops24** [comment]
Hi @JoeyAndres,
Thanks for your attention. Yes it's fixed now. You can close issue.
