### ISSUE TITLE
noop UTILITY

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#40]
I find myself using () => {} for a noop function. This should be abstracted away to reduce thinking time, especially for new developers.

**Comment by DanielDornhardt** [comment]
`_.noop()` : http://underscorejs.org/#noop

**Comment by DanielDornhardt** [comment]
Even the name is the same as you're thinking :)

**Comment by JoeyAndres** [comment]
Sure will definitely use that.
