### ISSUE TITLE
Investigate lag when transitioning to pages.

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#42]
Might be related to https://github.com/JoeyAndres/meteor-ionic/issues/26 issue in the backlog, or just some unnecessary js processing.

**Comment by JoeyAndres** [comment]
Wait for Meteor 1.3 release. I'll have to make some huge changes, that would be wasted if Meteor have a solution.

**Comment by JoeyAndres** [comment]
see https://github.com/peerlibrary/meteor-blaze-components

**Comment by cyclops24** [comment]
Hi @JoeyAndres I don't understand your link relation with issue title.

**Comment by JoeyAndres** [comment]
@cyclops24 I'm looking for a way to cache the template so that we don't have to create/recreate it. blaze-components seems to have a method that does just this. The link is just their for reminders so I can remember.

**Comment by cyclops24** [comment]
Hi @JoeyAndres, I test [pre-fork demo application](https://github.com/meteoric/demo) (based on [meteoric version](https://github.com/meteoric/meteor-ionic)) in my phone and it's page transition was more smoother than current version. I guess maybe something missed in new page transition implementation and no need template cache for fix this.

**Comment by JoeyAndres** [comment]
@cyclops24 Thanks for mentioning that. I haven't consider this for some reason. I will definitely get this under control.

**Comment by JoeyAndres** [comment]
Working on this now.

**Comment by cyclops24** [comment]
Have a good code man

**Comment by JoeyAndres** [comment]
@cyclops24 

### Base Line: (The code prior to optimization):

| Page | Start (original nick w.) | End (original nick w.) | Start (new) | End (new) | Duration(orignal) | Duration(new) | Diff | Diff % |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Action Sheet | 530 | 635 | 1360 | 1560 | 105 | 200 | 95 | 90.4% |
| Backdrop | 980 | 1070 | 2240 | 2400 | 90 | 160 | 70 | 77.7777% |
| Forms | 1480 | 1590 | 2940 | 3050 | 110 | 110 | 0 | 0 |
| Headers & Footers | 1980 | 2055 | 4240 | 4370 | 75 | 130 | 55 | 73.3333% |
| Lists | 3050 | 3150 | 4980 | 5160 | 100 | 180 | 80 | 80 |

### After removing ionIcon in **Lists** and **index.html**:

| Page | Start (original nick w.) | End (original nick w.) | Start (new) | End (new) | Duration(orignal) | Duration(new) | Diff | Diff % |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Action Sheet | 530 | 635 | 430 | 565 | 105 | 135 | 30 | 28.57142857 |
| Backdrop | 980 | 1070 | 1080 | 1180 | 90 | 100 | 10 | 11.11111111 |
| Forms | 1480 | 1590 | 1640 | 1780 | 110 | 140 | 30 | 27.27272727 |
| Headers & Footers | 1980 | 2055 | 2350 | 2495 | 75 | 145 | 70 | 93.33333333 |
| Lists | 3050 | 3150 | 3050 | 3150 | 100 | 100 | 0 | 0 |

## Analysis:

The conclusion is the new code introduce _ionItemContent_ template, to deal with the _complex_ state of a list (containing reorder,swipe,delete). This means, we effectively added another level of complexity, and there is just no way around it. Looking at the profile data, Tracker._runFlush is being called almost twice in the new code compared to the old code, meaning the template clean up stage is doing twice more work, hence the double the waiting when transition. 

## Solution (Draft):

Since ionIcon template is not in the standard (at least in 1.2.4), and can easily be replaced with `<i class="icon ....>`, I'm suggesting to deprecate ionIcon template. ionIcon is like using a class for a simple primitive variable, it doesn't makes sense. In the "optimize" table, _Headers & Footers_ still have ionIcon and it is almost double, as expected.

**Comment by JoeyAndres** [comment]
@cyclops24  Tell me if you have problem with this solution. If not, I'm going to deprecate ionIcon.

**Comment by cyclops24** [comment]
Hi @JoeyAndres
You tell right. I don't know why using blaze component rather than simple CSS class and ‍‍‍‍‍‍‍‍‍`<i>` tag for icon.
