### ISSUE TITLE
please update GUIDE.md

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#5]
Hi,
First thanks for maintaining this awesome package and continue mobile development with blaze.
I want to switch to your version but saw that you are using another version of [ionic-scss](https://github.com/sebakerckhof/meteor-ionic-sass/) package.
I suggest that update [GUIDE.md](https://github.com/JoeyAndres/meteor-ionic/blob/master/GUIDE.md) and add new notes about your version setup.

Thanks again @JoeyAndres.

**Comment by JoeyAndres** [comment]
@cyclops24 Yeah, I'll stop developing for a moment and focus a day or two for that. I've been meaning to do this for a while, but you know, addiction.

**Comment by cyclops24** [comment]
@JoeyAndres Thanks for your attention man.

**Comment by cyclops24** [comment]
Please create new label for **_documents issue**_ if it is useful.
For this issue and [this other](https://github.com/JoeyAndres/meteor-ionic/issues/11)

**Comment by JoeyAndres** [comment]
I will close this in favour of the doc site. meteoric-doc.com
