### ISSUE TITLE
Initial Slide in of Content - Where is that from? Should it be there? Can I disable it?

### ISSUE THREAD

**Issue by DanielDornhardt** [JoeyAndres/meteor-ionic#52]
Hi,

i'm trying to use this meteoric branch at the moment, and after getting around some other issues I'm working on, I noticed that the content always "slides in" from the right on the first load of any page, no matter if it's a subpage or the index page of the whole app.

See it here: http://jandres-ionic.meteor.com/ - just press reload and see the content slide in from the right.

I think that's probably to transition nicely between pages, but is it possible to disable this somehow for the first load?

A workaround would be fine for now, or maybe any information about where this is coming from in the code exactly.

Thanks and best wishes!

**Comment by DanielDornhardt** [comment]
For now i've just commented out the import of _transitions.scss in the package itself since I don't need transitions myself at the moment.

But I think it'd be nice to be able to control this better.

**Comment by JoeyAndres** [comment]
@DanielDornhardt Yeah, transitions is in its primitive stage. I have recently integrated original ionic controllers and this should handle that better.

**Comment by DanielDornhardt** [comment]
Hey, great to see you're busy about the project at the moment! I think Meteoric is a really valuable Mobile Framework for Meteor and it's great to see that it's not falling into disrepair.

**Comment by JoeyAndres** [comment]
Integration of ionic controllers should've fix this. Feel free to reopen this when problem arise.
