### ISSUE TITLE
Why no more "ionIcon"?

### ISSUE THREAD

**Issue by DanielDornhardt** [JoeyAndres/meteor-ionic#53]
Hi, sorry, but i'm curious: Why did you get rid of "ionIcon"? Is there an alternative we should be using?

**Comment by JoeyAndres** [comment]
@DanielDornhardt see #42 

The extra unnecessary template is introducing many delays on old devices. Since ion-icon is not really a directive in the original ionic, I discarded it and in #42, I showed performance comparison with/without it.

**Comment by DanielDornhardt** [comment]
Hi, thank you for the info and the link!

**Comment by JoeyAndres** [comment]
@DanielDornhardt no problem. I guess, I'll close this.
