### ISSUE TITLE
migration guide

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#54]
Add a [meteoric/meteor-ionic](https://github.com/meteoric/meteor-ionic) migration guide in the documentation website.

**Comment by cyclops24** [comment]
Hi @JoeyAndres 
As a suggestion I recommend to add version number to documentation website so users can simply know when it's update. Small version number (edition number) under title in [online document](http://meteoric-doc.meteor.com/) can be useful I guess.

**Comment by JoeyAndres** [comment]
@cyclops24 good idea.

**Comment by JoeyAndres** [comment]
I'm going to investigate auto-generating documentation for #5 and this #54 this weekend. ionic autogenerates from comment, this should be possible.

**Comment by JoeyAndres** [comment]
See https://github.com/jsdoc3/jsdoc/issues/1144

**Comment by JoeyAndres** [comment]
http://meteoric-doc.com/meteor-ionic-to-meteoric
