### ISSUE TITLE
upgrade to ionic2

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#6]
Hi,
Do you have any plan to upgrade meteor-ionic to [ionic2](http://ionicframework.com/docs/v2/getting-started/installation/) ?
ionic 2 has beautiful material design and many other new things.

**Comment by JoeyAndres** [comment]
@cyclops24 For sure.

**Comment by cyclops24** [comment]
@JoeyAndres I'm so happy to hear this. I think all awesome package based on blaze going to die for meteor 1.3 and after that.
I'm very happy now to see this awesome package going to live.
Please tell me if any type of help needed man.

**Comment by JoeyAndres** [comment]
@cyclops24 Sure. I'll clean up documentation. I have actually started http://meteoric-doc.meteor.com/, which is  interesting just by itself (pseudo clone of ionic doc). Once I cleaned things up and setup coding standards, I'll open this for pr.

**Comment by cyclops24** [comment]
@JoeyAndres Wooo, it's another good news tonight and very interesting for me, especially I love new meteoric icon.

Thanks @JoeyAndres you save my dreams man.

**Comment by cyclops24** [comment]
@JoeyAndres this issue same as [this](https://github.com/meteoric124/meteoric/issues/65) from @lorensr. So I close mine.
