### ISSUE TITLE
Links click events not triggering on ios with latest version anymore?

### ISSUE THREAD

**Issue by DanielDornhardt** [JoeyAndres/meteor-ionic#60]
Hi, I don't know excactly what made it break, but with the latest version on ios links don't seem to trigger click events properly.

A fast double-tap seems to work. Also when I change event handlers to "touchstart" instead of "click" they work as well.

I can observe this behavior in our app and also in the demo app.

I bisected it down to this commit: https://github.com/JoeyAndres/meteor-ionic/commit/6d5894ae323f6b9de03ec53f4954c77e3688fc83
- but of course it's a big one. I'll see whether I can find out more.

If you have any idea where this could stem from it'd be great if you could give me a hint!

Thanks & bye bye!

**Comment by DanielDornhardt** [comment]
Hi, I think it is because of the fastclick package which is actually included as a dependency of jandres:ionic.

See here: https://github.com/JoeyAndres/meteor-ionic/commit/6d5894ae323f6b9de03ec53f4954c77e3688fc83#diff-4947a0503762c3d79cc525d7a9876dfaR13

file lib/utils/tap.js, lines 13 - 16: 

> Out of the box, Ionic automatically removes the 300ms delay in order to make Ionic apps feel more "native" like. Resultingly, other solutions such as [fastclick](https://github.com/ftlabs/fastclick) and Angular's [ngTouch](https://docs.angularjs.org/api/ngTouch) should not be included, to avoid conflicts.

Now, when you remove fastclick from package.js and also make sure that it's not included via some other dependency (which isn't trivial it seems in some cases :) ) then order is restored to the universe and click events seem to be handled properly again.

As far as I can see so far though, I'm still testing.

**Comment by JoeyAndres** [comment]
@you are right. The Ionics event module is probably conflicting with fast click. Should we throw an error when fast click is detected? I've seen packages doing that.

**Comment by DanielDornhardt** [comment]
Hi, I think that'd be a terrific idea, especially because fastclick appears as a 2nd or third-level-dependency in at least a handful of common packages.

Especially the dependency on "meteor-platform" which contains fastclick, but isn't "current" anymore (should probably be exchanged for a newer set of packages or the required individual dependencies) leads to some packages still pulling in fastclick. It was a stupid amount of work figuring out which dependencies had fastclick still in the project.

I think it should be possible to check for `Package.fastclick` on the client to see if something's there and show a warning on the console?

**Comment by JoeyAndres** [comment]
OK will work on this immediately. I was planning on failing instead of just a warning.

**Comment by cyclops24** [comment]
Hi @JoeyAndres I have same issue on android too just want to tell man :wink:

**Comment by JoeyAndres** [comment]
fastclick click is now detected and error is thrown.
