### ISSUE TITLE
menu-close directive / attribute no longer working?

### ISSUE THREAD

**Issue by DanielDornhardt** [JoeyAndres/meteor-ionic#61]
Hi, it seems there's no way to make elements close the sidebar on / after click anymore?

the attribute menu-close (as seen in the demo) doesn't seem to work anymore, as does ion-data-menu-close or putting any of the above as classnames into the class - attribute.

And I don't even see how I can close the menu via javascript manually, which at least would it possible for me to create a workaround. Is there a straightforward way?

Could you maybe give an overview over the new features using the angular controllers etc. directly? I mean, is there some API we can use, a change in how we interact with meteoric / ionic?

By the way, would you see this fork as kind-of stable still or would you rather suggest people to not use it for projects needing some level of stability right now while you're mixing things up? Is stability (API-Stability and working stability) a primary concern for you at the moment?

Thanks and best wishes

Daniel

**Comment by JoeyAndres** [comment]
@DanielDornhardt Sorry for the problem. First and foremost, this thing is not stable. What browser/device are you testing menu-close? It works on mobile mode in chrome but once the width of the screen width >768, the exposeAsideWhen="large" is activated and the side menu is always expose then.

I'll amend README and mark this as UNSTABLE.

**Comment by DanielDornhardt** [comment]
Hi, i'm not sure what you mean with mobile mode in chrome... 

With the latest version, when added to the demo app I can't close the side menu by clicking  "Close Me" button inside the left side menu, no matter which size.

I think you got rid of the "snapper"? So I can't even close it manually. IonSideMenu.close() isn't implemented anymore either I think.

Sooo..

---

What I'd like to see would be a stable branch of the repo, call it master, if you will, and try to keep that mostly stable and feature - complete. Smaller bugfixes and non-breaking enhancements can go there and people can use it and contribute there so that the community would have a stable version to gather around.

I think this would be a good version to start with: https://github.com/JoeyAndres/meteor-ionic/commit/555065c35ef66d8494f9c4eee750d3bffb3ed356 - before you started integrating the original ionic controllers.

For the other things, do feature branches or an "experimental" branch to try them out and invite people to get feedback.

What do you think?

I really think meteor-ionic provides a lot of value and I'd be willing to add some small amount to eg. patreon to give you a regular additional income.

I'd be interested in learning / reading more about the new demo / docs page you did and what your overall goals and development "strategies" are.

Can I read about it in older tickets in the bugtracker? Do you have some kind of meta-information or discussion board where you talk about this project?

Thank you for your work

Daniel

PS: Edit: Ok, i see that you're already using multiple branches, and it still might be useful to keep one stable branch around I think. Best wishes again!

Edit 2: Changed the "recommended" stable version

**Comment by JoeyAndres** [comment]
@DanielDornhardt Yeah, I'll tag the meteoric one. My bad about that. I'll make an experimental branch as of this. I'll discuss this later (menu-close), work atm. If possible, is the menu-close outside or inside the ionSideMenuContainer?

**Comment by DanielDornhardt** [comment]
Hey Joey,

it's inside of `{{#ionSideMenuContainer}}` - but it's possible that it gets set dynamically / via a helper or somesuch or that it's actually rendered from inside another child template sometimes.

In the demo it's just plain inside of `{{#ionSideMenuContainer}}` . 

I couldn't actually find _any_ place where it would be read in the meteoric code - how should the detection of the attribute actually work? Which code should be triggered?

No worries about being at work etc, I think we're "asynchronous", you're from the 'Mericas and i'm from the 'europes it seems... so it's always a message here, another message tomorrow mostly :)

That's why I keep on writing such long texts as well so that you can at least get me :)

**Comment by JoeyAndres** [comment]
@DanielDornhardt It should be around here: https://github.com/JoeyAndres/meteor-ionic/blob/master/lib/blaze.js#L5 and then [here](https://github.com/JoeyAndres/meteor-ionic/blob/master/components/menuToggle/menuToggle.js#L18) it gets attached to a click event. I guess you can check if $element exist, or if the menuToggle "delegate" is being initialized in the first place.

In the mean time, I also have `meteoric.service.ionicSideMenuDelegate` and you can manually close sidemenu from their. I need to deprecate those IonSideMenu globals in favour of this more ionic like delegates (granted it's not being used like angular, its still cleaner imo),

**Comment by JoeyAndres** [comment]
Recent changes to template-scope/template-attribute directive should've fix this. Feel free to reopen if experiencing this issue again.
