### ISSUE TITLE
Introduce $scope, $preLink/$postLink for meteor templates.

### ISSUE THREAD

**Issue by JoeyAndres** [JoeyAndres/meteor-ionic#62]
We need a robust $scope, $preLink/$postLink so that the ionic controllers integrates easily.

Angular's **$preLink** is called when traversing downwards, then **$postLink**, when traversing upward the DOM tree.

Blaze only traverse DOM tree one way, upward with **onRendered**.

In angular, for a directive, **$preLink** is called first before **$postLink**. By the looks of it, we don't really have to follow this ordering. $postLink => $preLink would also satisfy.  That is when parent's $postLink (onRendered) is called, the child's $preLink can be called.

Note: This is based of [scope-prototype](https://github.com/JoeyAndres/meteor-ionic/tree/scope-prototype) branch. We will do it incrementally with hindsight this time.

**Comment by JoeyAndres** [comment]
@see [wip-62](https://github.com/JoeyAndres/meteor-ionic/tree/wip-62) for $scope prototype. See wip-62  branch for demo repo.

**Comment by cyclops24** [comment]
@JoeyAndres It's very interesting and I guess it's simplify many future integrations.

**Comment by JoeyAndres** [comment]
For documentation purposes, scoping is refactored out as a package in itself, https://github.com/meteoric124/meteor-template-scope. I have added tests and found some bugs. My current test cases are:
1. static templates
2. dynamic templates

The following cases that needs tests is layout or `{{yield}}`.
