### ISSUE TITLE
Please document this feature as an example in new docs

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#64]
Hi @JoeyAndres ,

I try to add dynamic title to my page with codes like this:

```
    {{#contentFor "headerTitle"}}
        <div>
            {{page.title}}
        </div>
    {{/contentFor}}

    <div>
        <h1>{{page.title}}</h1>
        {{page.text}}
    </div>
```

But template data (set w ironRouter) shows up in content but does not appear in headerTitle.
Finally I find [this related](https://github.com/meteoric/meteor-ionic/issues/31) question on Nick meteoric repository and change my code like below and everything OK now:

```
    {{#contentFor region="headerTitle" data=page}}
        <div>
            {{title}}
        </div>
    {{/contentFor}}

    <div>
        <h1>{{page.title}}</h1>
        {{page.text}}
    </div>
```

I think hidden features like this can many useful on real applications. I think it's good to add this as a new example to demo app or as a note to new document for others community members.

**Comment by JoeyAndres** [comment]
@see http://meteoric-doc.com/meteor-ionic-to-meteoric
