### ISSUE TITLE
Modals needs backdrop on large screen

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#68]
Hi @JoeyAndres ,
Please compare [Meteoric modal](http://meteoric-demo.com/modal) and [Ionic modal](http://codepen.io/ionic/embed/gblny?default-tab=result&slug-hash=gblny&theme-id=3572&height=568&user=ionic#result-box). It's not same now and Meteoric version needs some backdrops.

See above links or below images man:
![modal](https://cloud.githubusercontent.com/assets/8266479/14852509/fe2b7530-0c9b-11e6-905a-89b96867180c.png)

**Comment by cyclops24** [comment]
@JoeyAndres Meteoric modal also has an extra horizontal scroll that visible in above image.

**Comment by JoeyAndres** [comment]
done.
