### ISSUE TITLE
Prompt popup "TypeError: KeyboardEvent.code is undefined" on keyup

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#69]
Hi @JoeyAndres,

Please visit [this page](http://meteoric-demo.com/popup) click on **show prompt** button and type anything in input element, then client console show this error on keyup event:

```
TypeError: KeyboardEvent.code is undefined
...indow).on("keyup.ionPopup",function(e){e.which==KeyboardEvent.code.Escape&&we.cl...
```

**Comment by JoeyAndres** [comment]
@cyclops24 I go to the page. I think this is fixed with the recent updates to the core.

**Comment by JoeyAndres** [comment]
@cyclops24 Nevermind, the error is still there.

**Comment by JoeyAndres** [comment]
@cyclops24 I fixed it in beta.22
