### ISSUE TITLE
loading spinner not show

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#7]
Hi @JoeyAndres ,
I test demo app on a android device and go to [loading page](http://jandres-ionic.meteor.com/loading) but spinner animation and icons not shown for me after that I test online version and see that issue also there.

**Comment by JoeyAndres** [comment]
Should be fixed in 0.1.49. Tell me if fixed worked, and close this.

**Comment by cyclops24** [comment]
Hi @JoeyAndres I test new demo app and it's fixed. I close this issue.
Thanks...
