### ISSUE TITLE
SideMenu not working in demo app

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#70]
Hi @JoeyAndres,

unfortunately SideMenu not Working in related demo page: http://meteoric-demo.com/sideMenu

I don't know why. As I seen all thing is OK in code and no error exist in console.

**Comment by JoeyAndres** [comment]
Note: side-menu is disabled when back view is available (this can be change via config or something). Check again.

**Comment by cyclops24** [comment]
Thanks man. :+1:

**Comment by cyclops24** [comment]
@JoeyAndres please push latest demo commits to related repo. I need to learn SideMenu config that you said.

**Comment by JoeyAndres** [comment]
@cyclops24 Ill change the meteoric-doc

**Comment by JoeyAndres** [comment]
Add `enableMenuWithBackViews=true` to `ionSideMenus`
