### ISSUE TITLE
Docs related small issues and suggestion

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#72]
Hi @JoeyAndres I open this issue to post probable small issue on http://meteoric-doc.com
We can close this when all things OK. :wink:

**Comment by cyclops24** [comment]
# 1

Some times in http://meteoric-doc.com/meteor-ionic-to-meteoric page `meteoric:ionic` logo not load correctly like this:

![meteoric to meteoric124](https://cloud.githubusercontent.com/assets/8266479/14935336/0c3bc49c-0ee3-11e6-9654-db6a9daf5bed.png)

I check and see that `meteoric:ionic` logo refer to http://f.cl.ly/items/391y4708420P0H001k1G/meteoric.png but `meteoric124:meteoric` logo refer to http://meteoric-doc.com/meteoric-logo.png I think it's better to upload `meteoric:ionic` to http://meteoric-doc.com too.

**Comment by cyclops24** [comment]
# 2

`Getting Start` link in side menu refer to http://meteoric-doc.com/api/service/$ionicActionSheet that I think it's wrong.

**Comment by cyclops24** [comment]
# 3

`Docs` link in top menu refer to http://meteoric-doc.com/api/object/$ionicLoadingConfig that I think it's wrong.

**Comment by cyclops24** [comment]
# 4

I think it's better to add a favicon.ico to http://meteoric-doc.com

I create one icon based on meteoric logo here:
[favicon.ico.zip](https://github.com/meteoric124/meteoric/files/243550/favicon.ico.zip)

**Comment by JoeyAndres** [comment]
2 is now fixed.

**Comment by JoeyAndres** [comment]
1 is now fixed.

**Comment by JoeyAndres** [comment]
3 Shouldn't be there, we actually still use the original meteoric one. I'll remove it in the sidebar so no one can access it.

**Comment by JoeyAndres** [comment]
favicon.ico is now integrated. Thank you for that.

**Comment by JoeyAndres** [comment]
I'll close this. I think we should stick with one story per issue so we can keep track of them.

**Comment by cyclops24** [comment]
@JoeyAndres you right. OK man.
