### ISSUE TITLE
Remember list position when back from subpage ?

### ISSUE THREAD

**Issue by daveeel** [JoeyAndres/meteor-ionic#73]
Say in the demo: meteoric-demo.com, when I click "Radio" to the radio page, then "Back" to the big list, the expected behaviour is to stay at where I enter subpage. However the list goes to start from the first item "Action Sheet". Is it possible to remember the parent list position ?

**Comment by JoeyAndres** [comment]
@daveeel From the original ionic, this is handled by caching the last page. I'll try to make a work around by having history keep track of scroll position or something. I'll post a branch here to test.

**Comment by JoeyAndres** [comment]
@daveeel I have pushed beta.18. Tell me how it goes.

**Comment by daveeel** [comment]
Thanks @JoeyAndres , it's now much better. However I noticed if the list item at top is not aligning exactly at it's top margin (should be most cases), the list will first align to the item's top margin, then jump to the expected original location. That makes it feel a bit unnatural. Test results are the same on both iPhone mobile Safari and Mac Chrome simulation.

**Comment by JoeyAndres** [comment]
@daveeel Ok, I'll get rid of the animation feature, just a matter of passing false instead of true. You are right, that is weird. I'll do this after work.

**Comment by JoeyAndres** [comment]
@daveeel I have pushed beta.20. Tell me again how it goes.

**Comment by daveeel** [comment]
The demo is great now 👍
