### ISSUE TITLE
header bar transition on page change not working

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#8]
Hi @JoeyAndres ,
First excuse me if I post many issue. I see that transition on route change (page change animation) not working now.
You can compare [this](http://meteor-ionic.meteor.com/) and [this](http://jandres-ionic.meteor.com/).

**Comment by JoeyAndres** [comment]
@cyclops24 Don't worry about posts. I need as much feedback as possible. 

Anyway, I'm gonna see if ionic 1.2 changed their transition. This is usually in css.

**Comment by cyclops24** [comment]
@JoeyAndres Do you switch to ionic 1.2 now?

**Comment by JoeyAndres** [comment]
@cyclops24 yes, I'm doing my development around 1.2 atm. I'll update this post once I got the documentation going.

**Comment by cyclops24** [comment]
@JoeyAndres I think header bar transition not working at all. Do you see that issue?

**Comment by JoeyAndres** [comment]
@cyclops24 Yeah. I'm working on that atm. This part is so ugly (globals in 10 different places), that it took me all sunday. 

There is actually two problem, header transition and page transition. What I worked on for today is just page transition (I'm sure the solution is easy for header once page transition is fixed). The following is the prototype solution:

http://jandres-ionic-dev.meteor.com/

This is a different demo site (-dev) and is not pushed. So don't bother compiling this to native android. I'll make the solution more robust, and make the code base cleaner, so the next person won't have a hard time and waste their Sunday on this.

**Comment by JoeyAndres** [comment]
@cyclops24 I have figured a clean and blaze solution for this problem. I'll upload the code tomorrow. I'll sleep now. Anywayz, I appreciate your input in this project. Would've been impossible to spot those without input.

**Comment by cyclops24** [comment]
@JoeyAndres Thank you for your kindness. I love meteoric and try to help with report issues. Excuse me for my bad English. :wink: 
I'm waiting for your new solution ( :+1:  ).

**Comment by JoeyAndres** [comment]
@cyclops24 Can't push the solution yet. The fix is easy, but I want this done right since transitions will be the most use feature.

http://jandres-ionic-dev.meteor.com/ is updated

The page transition is now mature, except I need to catch all "back" events. Header is yet to mature. The original version skipped a lot, so lots of work to be done. I'll push the code tomorrow. Today is simply premature.

**Comment by JoeyAndres** [comment]
@cyclops24 I think I have completed page/header transitions. It took a while, but its here. http://jandres-ionic.meteor.com/ now have the demo, and master branch 0.1.47-alpha1 should have the new fix. The demo master branch also updated.

I will remove "alpha" when you are satisfied with the result. It's purely almost purely css animation. Once you are satisfied, I'll update the docs for any changes.

**Comment by cyclops24** [comment]
@JoeyAndres it's worked and well. Thanks man.
But I think animation speed a little high I think a little slower animation is better and more like original ionic page transition.

**Comment by JoeyAndres** [comment]
@cyclops24 Yeah. That is true. I'll look into that and I'll push another one. Just woke up and got to work now.

**Comment by JoeyAndres** [comment]
@cyclops24 I have pushed the fixes at 0.1.47-alpha2. The demo sites are also up to date. Tell me if those bug still exist, and I'll get rid of the "alpha".

**Comment by cyclops24** [comment]
Hi @JoeyAndres ,
I test new demo on my devices (one with android 4.2.1 and one with android 5)
Android 4.2.1 animation not shown at all. (I think it's because of the same issue with [this](https://github.com/JoeyAndres/meteor-ionic/issues/10)) and android 5 animation not smooth (some laggy) I think. I don't know why but it's not same as web result.
Do you test this on real device?

**Comment by JoeyAndres** [comment]
Yeah. I have ran 

``` bash
meteor run android-device
```

and it is actually faster than the web result. I use zenfone, which is relatively fast. What is your device? I'll go look for device like that?

If you want a baseline of the animations in android, see https://play.google.com/store/apps/details?id=com.ionicframework.demoapp862762&hl=en. You might be seeing ios animation in web view, which have "slower" and lots more movement, and looks better to be frank.

**Comment by cyclops24** [comment]
I have a HUAWEI G610 phone (android 4.2.1 - Quad Core CPU , ...) and a NEXUS 7 tablet (NEXUS 1 WiFi Series with android 5)

**Comment by JoeyAndres** [comment]
@cyclops24 I have emulated 4.2.2 and transitions went great. And again, I used it with my own phone, zenfone with android 5.x and it went well there too.

**Comment by cyclops24** [comment]
@JoeyAndres Thanks for your attention. I also test [ionic framework Demo](https://play.google.com/store/apps/details?id=com.ionicframework.demoapp862762&hl=en) and it's demo also not smooth on my phone. Maybe it's my phone issue.
I think that's better to close this issue. I also try to find my phone problem with ionic.

**Comment by JoeyAndres** [comment]
@cyclops24 No problem.
